### ISSUE TITLE
Use a single git repo for all tutorials

### ISSUE THREAD

**Issue by yjlintw** [SI539/tutorials#2]
1. Should we use a single git repo for all tutorials, and categorize them under different folders?
2. Are we using GitHub wiki's repo to store those tutorial and add it as a submodule into the  tutorials repo? Or is there any more elegant way to do that?

**Comment by nishanbose** [comment]
1. Let's use the git repo - tutorials for all tutorial and categorize them under different folders
2. Let's avoid using wiki for tutorials but we could use the wiki for the news letters

**Comment by nishanbose** [comment]
Under each folder, we should rename the actual tutorial to "readme.md" so that it is easily visible as soon as a user visits that folder.

For example the current git folder has a file named "SetUpGitServer.md" which should be renamed to "readme.md"

**Comment by yjlintw** [comment]
Sounds a good idea. I don't have my computer at my hands right now. Feel
free to modified it. I believe you have the right permission to do that. If
not, please let me know.

On Tuesday, September 8, 2015, Nishan Bose notifications@github.com wrote:

> Under each folder, we should rename the actual tutorial to "readme.md" so
> that it is easily visible as soon as a user visits that folder.
> 
> For example the current git folder has a file named "SetUpGitServer.md"
> which should be renamed to "readme.md"
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/SI539/tutorials/issues/2#issuecomment-138595493.

## 

Sent from Gmail Mobile
